version: '3.1'
services:
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: security2024
      MYSQL_USER: frederico
      MYSQL_PASSWORD: security2024
      MYSQL_DATABASE: springsecurity
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308 
    ports:
       - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network
  docker-spring-boot:
    image: fredericoramos/springsecurity
    restart: always
    build: 
      context: .
    working_dir: /springsecurity
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/springsecurity
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: sicred2024
    ports:
      - 8080:8080
    expose:
      - 8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network 
volumes:
 dbdata:
  driver: local	
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/srv/db-data'
networks:
 erudio-network:
   driver: bridge  


